# dbt_project.yml
name: 'grandmas_cafe'
version: '1.0.0'
config-version: 2
dbt-cloud:
    project-id: 70506183154133

profile: 'grandmas_cafe'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  grandmas_cafe:
    staging:
      +materialized: view